# Generated by Django 2.0.2 on 2018-05-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sci_name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirdPollColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birddb.Bird')),
            ],
        ),
        migrations.CreateModel(
            name='BirdReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_name', models.CharField(max_length=50, unique=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birddb.Bird')),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sizes_sum', models.FloatField(default=0)),
                ('num_entries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidBird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=400)),
                ('call', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birddb.Genus'),
        ),
        migrations.AddField(
            model_name='bird',
            name='web_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birddb.WebData'),
        ),
    ]
