# Generated by Django 2.0.2 on 2018-05-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='sci_name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
