# Generated by Django 2.0.2 on 2018-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birddb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='img_lic',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='webdata',
            name='img_rec',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
