# Generated by Django 2.0.2 on 2018-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birddb', '0002_auto_20180525_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='call_lic',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='webdata',
            name='call_rec',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
