# Generated by Django 2.0.2 on 2018-05-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birddb', '0004_auto_20180526_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='web_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birddb.WebData'),
        ),
    ]
